# This GitHub action runs your tests for each commit push and/or PR. Optionally
# you can turn it on using a cron schedule for regular testing.
#
name: Tests
concurrency: test
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'
  # For systems with an upstream API that could drift unexpectedly (like most SaaS systems, etc.),
  # we recommend testing at a regular interval not necessarily tied to code changes. This will
  # ensure you are alerted to something breaking due to an API change, even if the code did not
  # change.
  # schedule:
  #   - cron: '0 13 * * *'
jobs:
  # ensure the code builds...
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: |
          go build -mod=vendor -v .
  # run acceptance tests in a matrix with Terraform core versions
  test:
    name: Matrix Test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform:
          - '0.12.*'
          - '0.13.*'
          - '0.14.*'
          - '0.15.*'
          - '1.0.*'
          - '1.1.*'
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
        id: go

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      # Random sleep so acceptance tests do not collide creating objects on Chef Server
      - name: Wait
        uses: 1itachi/sleep-random@v1.0.0
        with:
          minutes: '2'
          random: 'true'

      - name: TF acceptance tests
        timeout-minutes: 10
        env:
          GOFLAGS: '-mod=vendor'
          TF_ACC: '1'
          CHEF_SERVER_URL: http://127.0.0.1:8889
          CHEF_CLIENT_NAME: chef-zero
          CHEF_KEY_MATERIAL: ${{ secrets.CHEF_KEY_MATERIAL }}

        run: |
          go test -v -cover ./internal/provider/

    services:
      chef-zero:
        image: osuosl/chef-zero
        ports:
          - 8889:8889
